# Generated by Django 4.0.3 on 2022-04-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='no_of_rooms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='no_of_washrooms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
